apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsu-python-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: devsu-python.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsu-python-service
                port:
                  number: 80
