apiVersion: v1
kind: Secret
metadata:
  name: devsu-python-secret
type: Opaque
data:
  # Base64 encoded values
  # SECRET_KEY=django-insecure-key (ZGphbmdvLWluc2VjdXJlLWtleQ==)
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWtleQ==
